### ISSUE TITLE
Table content

### ISSUE THREAD

**Issue by rexdefuror** [Epstone/Simple-MVC-User-Management#1]
Hello, I'm not sure if you could call this an issue, but still I think it could help both me, and others interested in this project.

I've tested a bit of this code, and played around with it while researching `UserManagement`. Now i wanted to try to limit the Values user table is showing, like removing `ID` from it. How would it be possible to do that?

**Comment by Epstone** [comment]
Would it be enough to just hide the column through css in the browser? I'll just add classes which makes it easier to do so.
If you don't want the user Id or any other column at all transferred from the server to the browser you have to edit the controller method (1) building the user json object and also the js piece building the html row (2).
(1) https://github.com/Epstone/Simple-MVC-User-Management/blob/master/SimpleMvcUserManagement/UserManagementController.cs#L80
(2)https://github.com/Epstone/Simple-MVC-User-Management/blob/master/SimpleMvcUserManagement/Scripts/simple-user-management.js#L376

**Comment by rexdefuror** [comment]
Yeah this works fine. 
Also, I get an error when I try to delete user. "It must be type System.Grid".
All of this works quite nicely within my local dev environment. But when I place it on server, it displays the table for user but does not populate it. What do you think it could be?

**Comment by Epstone** [comment]
Could you post the full exceptions please?
What is returned from the server when calling the "GetAllUsers" action? Please have a look in your firebug or chrome Network tab.

**Comment by rexdefuror** [comment]
`{"message":"The provider user key supplied is invalid.  It must be of type System.Guid.\r\nParameter name: providerUserKey","isSuccess":false,"data":null}`

This is the full response I get from firebug.

What do you think about my server issue, by the way?
Server response is this
`<h2>404 - File or directory not found.</h2>`
`<h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>`

28d484b5-8f2f-4e11-8f47-35c23beb972f <-- this is my UserID

**Comment by rexdefuror** [comment]
I've updated the previous message with full exceptions.

I'm guessing I might've messed up with publishing the project... Although I did everything "by-the-book" for multi-project solutions.

**Comment by Epstone** [comment]
hmm.. which membership provider are you using? The DeleteUser Method received the userId as string which might be the problem. It's working fine here for the MySql membership provider. I switched to object but then it is casted as string[] internally.
Do you have a stacktrace for me? Or debug it yourself somehow :)

Issue 2 should be a routing problem, but it doesn't make much sense as the DeleteUser Method is called fine in the same application?! 
Sorry I'm out of ideas...

**Comment by rexdefuror** [comment]
I think you misunderstood me a bit :)

Delete problem occurs on local where I can see everything fine. I'm using SQL Server Compact 4.0 ASP.NET Membership provider.
As for stacktrace, I'm bit noobish hence all the stupid questions ^_^ I know what it is just no idea how to get it with VS2010 :S sorry

On server nothing works except the Html for table. It shows the table header and pager and that's all.

**Comment by rexdefuror** [comment]
I wondered, could you mark where you stated the ID type?

**Comment by Epstone** [comment]
The Stacktrace is part of the Exception which you would see while debugging e.g. 
But the DeleteUser thing should be solved now, as I switched to using the username for deletion. This even makes more sense for the membership service than using the user Id.
Please pull the latest version.

The Error 404 is really hard for me to reproduce. Maybe this could help for debugging the routes. 
http://haacked.com/archive/2011/04/13/routedebugger-2.aspx

**Comment by rexdefuror** [comment]
Thanks a lot. I will leave the issue open 'till I find the trick behind the server issue, I do have few notions. Will post it here and close the issue so people with similar troubles will have something to refer to.
Thanks again.

**Comment by rexdefuror** [comment]
I've tried and all works well in local, still same issue on server :(

Thanks again for all the help. On to debugging ^_^

**Comment by rexdefuror** [comment]
Hello again, well I've found time and messed around this yet again, I've found that the URL for Actions on server is wrong. Mainly because it's strong coded, and for that reason doesn't work for me. I've checked several solutions and tried to replace URLs on `$.post('/{controllerName}/GetAllUsers', {}, function (users).....` for example, with `'<%=Url.Action("GetAllUsers, "{controllerName}") %>'`, I know that I should use `JSON.stringify` somewhere but no idea where...

Any ideas? :)

**Comment by Epstone** [comment]
Just to clear things up for me ;)
1. Is the same application running fine in dev environment but not on production server??
2. Are you calling UserManagementController.RegisterMe(); as first method (after ignore..) in RegisterRoutes @ global.asax

If we want to generate the urls dynamically by the Url helper we could change the MyHtml methods to be extension methods for the regular HtmlHelper. Than replace the Url's in the html/js string from the ressource file. 

My assumption on the hardcoded url's was that if we register the user management route as first it would work fine for anything starting with .../UserManagement/...

**Comment by rexdefuror** [comment]
1. Yes dev environment is working perfectly (VS2010)
2. Yes I am calling `UserManagementController.RegisterMe()` as first method after ignore...

There is no need to generate Urls dynamically or anything, i just want it to work :D
This is just what I found by browsing through problems, mainly this is not an unknown issue, there are references all over but they are using different type of posting which I don't understand enough to use in this project :( Hence I'm screaming for help! :'(

**Comment by Epstone** [comment]
Believe me, I know your situation ;) here is another shot in the dark... 
Is there a directory called "UserManagement" somewhere in your ASP.NET directory on root level?? Just existing on the server...
http://code-inside.de/blog/2012/07/12/error-404-directory-schlgt-asp-net-mvc-routing/ (german sorry)
http://www.west-wind.com/weblog/posts/2012/Apr/05/Physical-Directories-vs-MVC-View-Paths

**Comment by rexdefuror** [comment]
No such directory what so ever. I've checked also that I didn't copy files included in your project, it's just the DLL and the debug file that are imported as reference on publishing.

**Comment by Epstone** [comment]
ok.. sorry I have to give up there without access to the server. Even with access it might take a while ;)

**Comment by rexdefuror** [comment]
Ok. I'll manage somehow I guess. Thanks and sorry for the trouble. If you get an idea contact me on admin@rexdefuror.com. Cheers

**Comment by Epstone** [comment]
np, thank you too for your input and the other improvement on user deletion thing! See you, when someone finds a solution on the 404.
