### ISSUE TITLE
Needs update to Identity 2.0

### ISSUE THREAD

**Issue by lordofscripts** [Epstone/Simple-MVC-User-Management#4]
This excellent package works with the now extremely outdated standard ASP.NET Membership. It would be nice if it is updated to use Identity 2.0, or perhaps make it support both.

**Comment by Epstone** [comment]
Sorry, but Ive no time to continue working on these membership features.
Feel free to fork the project!

Am Dienstag, 16. September 2014 schrieb lordofscripts :
